### ISSUE TITLE
Apple silicon `missing field napi_versions at line 34 column 3`

### ISSUE THREAD

**Issue by felixfiskare** [mmomtchev/node-gdal-async#186]
I'm using an Apple M2 Pro.

When I try to open a grib2 file

```
import * as gdal from 'gdal-async'

const ds1: gdal.Dataset = gdal.open(
        'x/icon-eu_europe_regular-lat-lon_single-level_2024120318_000_WW.grib2')
```

I get an error.

```
 ⨯ Error: missing field `napi_versions` at line 34 column 3

Debug info:
- Execution of get_written_endpoint_with_issues failed
- Execution of <AppEndpoint as Endpoint>::write_to_disk failed
- Execution of Project::emit_all_output_assets failed
- Execution of VersionedContentMap::insert_output_assets failed
- Execution of all_assets_from_entries failed
- Execution of AppEndpointOutput::output_assets failed
- Execution of AppEndpoint::output failed
- Execution of NodeJsChunkingContext::entry_chunk_group failed
- Execution of ModuleResolveResult::primary_output_assets failed
- Execution of resolve_node_pre_gyp_files failed
- missing field `napi_versions` at line 34 column 3
    at binary
      30 |     "hosting": {
      31 |       "provider": "github",
      32 |       "repo": "mmomtchev/node-gdal-async"
      33 |     }
         |   v
      34 +   },
         |   ^
      35 |   "repository": {
      36 |     "type": "git",
      37 |     "url": "https://github.com/mmomtchev/node-gdal-async.git"
      38 |   },
    at withErrorCause (X/node_modules/next/dist/build/swc/index.js:413:19)
    at async EndpointImpl.writeToDisk (X/node_modules/next/dist/build/swc/index.js:596:20)
    at async handleRouteType (X/node_modules/next/dist/server/dev/turbopack-utils.js:392:41)
    at async Object.ensurePage (X/node_modules/next/dist/server/dev/hot-reloader-turbopack.js:651:17)
    at async DevBundlerService.ensurePage (X/node_modules/next/dist/server/lib/dev-bundler-service.js:18:20)
    at async DevServer.ensurePage (X/node_modules/next/dist/server/dev/next-dev-server.js:551:9)
    at async Object.ensure (X/node_modules/next/dist/server/dev/next-dev-server.js:169:17)
    at async DevRouteMatcherManager.matchAll (X/node_modules/next/dist/server/future/route-matcher-managers/dev-route-matcher-manager.js:96:13)
    at async DevRouteMatcherManager.match (X/node_modules/next/dist/server/future/route-matcher-managers/default-route-matcher-manager.js:155:26)
    at async NextNodeServer.handleCatchallRenderRequest (X/node_modules/next/dist/server/next-server.js:228:31)
    at async DevServer.handleRequestImpl (X/node_modules/next/dist/server/base-server.js:817:17)
    at async X/node_modules/next/dist/server/dev/next-dev-server.js:339:20
    at async Span.traceAsyncFn (X/node_modules/next/dist/trace/trace.js:154:20)
    at async DevServer.handleRequest (X/node_modules/next/dist/server/dev/next-dev-server.js:336:24)
    at async invokeRender (X/node_modules/next/dist/server/lib/router-server.js:173:21)
    at async handleRequest (X/node_modules/next/dist/server/lib/router-server.js:350:24)
    at async requestHandlerImpl (X/node_modules/next/dist/server/lib/router-server.js:374:13)
    at async Server.requestListener (X/node_modules/next/dist/server/lib/start-server.js:141:13) {
  [cause]: [Error: missing field `napi_versions` at line 34 column 3
  
  Debug info:
  - Execution of get_written_endpoint_with_issues failed
  - Execution of <AppEndpoint as Endpoint>::write_to_disk failed
  - Execution of Project::emit_all_output_assets failed
  - Execution of VersionedContentMap::insert_output_assets failed
  - Execution of all_assets_from_entries failed
  - Execution of AppEndpointOutput::output_assets failed
  - Execution of AppEndpoint::output failed
  - Execution of NodeJsChunkingContext::entry_chunk_group failed
  - Execution of ModuleResolveResult::primary_output_assets failed
  - Execution of resolve_node_pre_gyp_files failed
  - missing field `napi_versions` at line 34 column 3
      at binary
        30 |     "hosting": {
        31 |       "provider": "github",
        32 |       "repo": "mmomtchev/node-gdal-async"
        33 |     }
           |   v
        34 +   },
           |   ^
        35 |   "repository": {
        36 |     "type": "git",
        37 |     "url": "https://github.com/mmomtchev/node-gdal-async.git"
        38 |   },] {
    code: 'GenericFailure'
  }
}

```

I installed the package from source (https://github.com/mmomtchev/node-gdal-async/issues/30#issuecomment-1275888379).
I installed the latest release and I also tried the latest commit ( `"gdal-async": "github:mmomtchev/node-gdal-async#38def27e417bde7a2760855b4c013b1199b94136"` ) because my brew installed Gdal is version 3.10.0.

Any idea how to fix this error?

**Comment by mmomtchev** [comment]
You are doing much more than you say, because I see `next.js`. Maybe you are using some of my methods for using native modules such as `gdal-async` on the server side, but whatever you patched - because you must have patched something - is not patched correctly because `gdal-async` does not use Node-API.

As for Apple Silicon, I currently do not have access to Apple Silicon. The projects I work for which run without modifications, are automatically built, but this is not the case for `gdal-async`. I have been proposed access to an Apple Silicon by people taking part in the extortion, however I cannot accept any donations from people insisting to show that the money is linked to this affair.

**Comment by felixfiskare** [comment]
In the meantime, I used a Python based approach. I will reopen this ticket once I can give you a minimum reproducible error for this.
