### ISSUE TITLE
Unable to use node-gdal-async 

### ISSUE THREAD

**Issue by Rajprabhu14** [mmomtchev/node-gdal-async#47]
I am using docker to run nodel-gdal in my project

My error:
 /home/app/node_modules/gdal-async/lib/gdal.js:380
       return driver.create.apply(driver, args)
                            ^

 Error: PostgreSQL driver doesn't currently support database creation.
 Please create database with the `createdb' command.
     at Object.open (/home/app/node_modules/gdal-async/lib/gdal.js:380:28)
     at getShapeDataset (/home/app/qaqc/QaqcBase.js:99:28)
     at module.exports.isAnotherProcessRunning (/home/app/qaqc/QaqcBase.js:222:16)
     at /home/app/server.js:45:22
     at Layer.handle [as handle_request] (/home/app/node_modules/express/lib/router/layer.js:95:5)
     at next (/home/app/node_modules/express/lib/router/route.js:144:13)
     at Route.dispatch (/home/app/node_modules/express/lib/router/route.js:114:3)
     at Layer.handle [as handle_request] (/home/app/node_modules/express/lib/router/layer.js:95:5)
     at /home/app/node_modules/express/lib/router/index.js:284:15
     at Function.process_params (/home/app/node_modules/express/lib/router/index.js:346:12)
	 
Versions
postgres version 14.5
Node.js v18.12.1
GDAL 3.2.2

**Comment by zy6p** [comment]
This is a common problem with the postgres driver, most likely because the database connection information is incorrect, role does not have permission to the database, etc.
